// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzbsrxlntskektydujpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6YnNyeGxudHNrZWt0eWR1anBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwOTUwMzcsImV4cCI6MjA1NTY3MTAzN30.DqO5x87mcJ8DDfHhqiyKkyoHhv5ii3-wIt-WQX8A7PY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);